[package]
name = "flocking"
version = "0.1.0"
authors = ["Htet Aung Shine <h@shine.rocks>"]

[dependencies]
rand = "0.5.4"
piston = "0.37.0"
piston2d-graphics = "0.26.0"
pistoncore-glutin_window = "0.47.0"
piston2d-opengl_graphics = "0.53.0"